### ISSUE TITLE
Segmentation fault when reading /etc/passwd

### ISSUE THREAD

**Issue by aragaer** [borkdude/babashka.curl#29] opened 2020-11-21 11:22 UTC
```
$ bb '(curl/post "https://google.com")'
Segmentation fault

$ strace bb '(curl/post "http://google.com")'
...
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 5
fstat(5, {st_mode=S_IFREG|0644, st_size=1934, ...}) = 0
lseek(5, 0, SEEK_SET)                   = 0
read(5, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 1934
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xe5} ---
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x702d070} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

What else should I check?

**Comment by borkdude** [comment] 2020-11-21 11:31
@aragaer I'm getting:

```
$ bb '(curl/post "https://google.com")'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  babashka.curl: status 405
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (curl/post "https://google.com")
   ^--- babashka.curl: status 405
```

This is roughly the command it will generate to curl:

```
curl --silent --show-error --location --dump-header /var/folders/2m/h3cvrr1x4296p315vbk7m32c0000gp/T/babashka.curl2950274560201676838.headers --request POST https://google.com
```
Could you try that command without bb and see what this does?

**Comment by aragaer** [comment] 2020-11-21 11:53
I had to change the "--dump-header" path to /tmp/something and got google's captcha page. Basically that worked, no segmentation fault.

**Comment by borkdude** [comment] 2020-11-21 12:01
@aragaer Hmm.

babashka.curl creates a tmp header file for reading the headers that curl got back:

This would be a small repro:

```
$ bb -e '(spit (File/createTempFile "babashka.curl" ".headers") "")'
```

Can you check if this fails with the same problem?

**Comment by aragaer** [comment] 2020-11-21 12:26
Worked without error and no output. `strace -e file` shows that it created a file in /tmp
```
stat("/tmp/babashka.curl4998014343453406646.headers", 0x7fffeb77dce0) = -1 ENOENT (No such file or directory)
open("/tmp/babashka.curl4998014343453406646.headers", O_RDWR|O_CREAT|O_EXCL, 0666) = 5
open("/tmp/babashka.curl4998014343453406646.headers", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
+++ exited with 0 +++
```

**Comment by borkdude** [comment] 2020-11-21 13:09
@aragaer I'm not sure how to reproduce your problem. I also tried on linux. Why is your /etc/passwd being read? This has nothing to do with the curl request it seems?

**Comment by aragaer** [comment] 2020-11-21 13:32
That's exactly why I don't understand what is happening. curl itself doesn't open /etc/passwd. I also don't see any `exec` or anything like that in strace output.

**Comment by borkdude** [comment] 2020-11-21 14:01
@aragaer Could you try the same thing using this repo as a JVM lib?

**Comment by aragaer** [comment] 2020-11-21 16:27
How do I do that? I mean I did clone it but don't know about the JVM part.

**Comment by borkdude** [comment] 2020-11-21 16:32
For example, from within the repo:

```
$ clj
Clojure 1.10.1
user=> (require '[babashka.curl :as curl])
nil
user=> (curl/post "https://google.com")
Execution error (ExceptionInfo) at babashka.curl/request (curl.clj:252).
babashka.curl: status 405
user=>
```

See https://clojure.org/guides/getting_started#_clojure_installer_and_cli_tools for how to install `clj`.
Make sure you're running with the exact same user to replicate the situation with bb as close as possible.

We could also try the same with babashka from the JVM. I'll explain if needed after you try this.

**Comment by aragaer** [comment] 2020-11-21 16:33
```
$ bb
Babashka v0.2.3 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (curl/post "https://google.com")
Segmentation fault
```

**Comment by borkdude** [comment] 2020-11-21 16:36
This is not the JVM, this is bb invoked as a binary?

**Comment by aragaer** [comment] 2020-11-21 16:37
Yeah, probably.
Installed clj. Result:
```
Clojure 1.10.1
user=>  (curl/post "https://google.com")
Syntax error compiling at (REPL:1:1).
No such namespace: curl
user=> (curl/post "https://google.com")
Syntax error compiling at (REPL:1:1).
No such namespace: curl
user=> (require '[babashka.curl :as curl])
nil
user=> (curl/post "https://google.com")
Execution error (ExceptionInfo) at babashka.curl/request (curl.clj:252).
babashka.curl: status 429
```

**Comment by borkdude** [comment] 2020-11-21 16:41
@aragaer ok, next step. Try with bb as a whole from the JVM:

```
$ git clone https://github.com/borkdude/babashka --recurse-submodules
$ cd babashka
$ clj
Clojure 1.10.2-alpha2
user=> (require '[babashka.main :as bb])
nil
user=> (bb/main "(curl/post \"https://google.com\")")
```

**Comment by aragaer** [comment] 2020-11-21 16:43
```
Clojure 1.10.2-alpha2
user=> (require '[babashka.main :as bb])
Syntax error (ClassNotFoundException) compiling at (babashka/impl/classes.clj:288:20).
java.lang.ProcessHandle
```
Which is strange - I just had clojure 1.10.1

**Comment by borkdude** [comment] 2020-11-21 16:44
Ah sorry about that. Babashka needs Java 11. You are probably using 8.

**Comment by aragaer** [comment] 2020-11-21 16:58
Yes, I only have java 1.8.

**Comment by borkdude** [comment] 2020-11-21 17:04
@aragaer I can help you with running Java 11, but before that we can try another thing.

Try a bb from master compiled with 20.2.0: https://13167-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.4-SNAPSHOT-linux-amd64.zip

And try bb from master compiled with GraalVM 20.3.0: 
https://13094-201467090-gh.circle-artifacts.com/0/release/babashka-0.2.4-SNAPSHOT-linux-amd64.zip

I am curious if you see a difference with either one. Note that 0.2.3 also was compiled with 20.2.0 but 20.3.0 came out a few days ago.

**Comment by aragaer** [comment] 2020-11-21 17:10
Both work.
```
$ ls -l bb-0.2.4-20.*
-rwxr-xr-x 1 aragaer aragaer 73375984 Nov 21 13:54 bb-0.2.4-20.2.0
-rwxr-xr-x 1 aragaer aragaer 73109576 Nov 19 21:48 bb-0.2.4-20.3.0
$ ./bb-0.2.4-20.2.0 '(curl/post "https://google.com")'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  babashka.curl: status 429
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (curl/post "https://google.com")
   ^--- babashka.curl: status 429

----- Stack trace --------------------------------------------------------------
babashka.curl/post - <built-in>
user               - <expr>:1:1

$ ./bb-0.2.4-20.3.0 '(curl/post "https://google.com")'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  babashka.curl: status 429
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (curl/post "https://google.com")
   ^--- babashka.curl: status 429

----- Stack trace --------------------------------------------------------------
babashka.curl/post - <built-in>
user               - <expr>:1:1
```

**Comment by borkdude** [comment] 2020-11-21 17:12
Good to hear, although we still don't know what caused it. Can you try re-installing bb 0.2.3 and see if you have the same problem? Maybe your binary is corrupt somehow?

**Comment by aragaer** [comment] 2020-11-21 17:15
I've checked and the binary I use is equal to the one in babashka-0.2.3-linux-static-amd64.zip archive (I've redownloaded the archive and compared it to what I had too).

**Comment by borkdude** [comment] 2020-11-21 17:16
I don't recommend using the static one unless you have to like on Alpine. Can you try with the non-static one?

**Comment by aragaer** [comment] 2020-11-21 17:20
Interesting. Non-static one works. The static one worked for me when I downloaded it almost exactly one month ago.

**Comment by borkdude** [comment] 2020-11-21 17:21
Weird! Glad it's solved. The static one is intended for Alpine. The babashka Docker image was based on that, but now we moved it to Ubuntu because there were other problems too. I think we can close this now. Glad it's solved.

**Closed by borkdude** 2020-11-21 17:21 UTC
